name: Book Tennis Court

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date de réservation (YYYY-MM-DD)'
        required: true
        default: '2025-06-16'
        type: string
      hour:
        description: 'Heure (7, 7.5, 8, 8.5, etc.)'
        required: true
        default: '7'
        type: string
      account:
        description: 'Compte à utiliser (1 ou 2)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'

jobs:
  book:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run booking script
      env:
        TENNIS_USERNAME: ${{ secrets.TENNIS_USERNAME }}
        TENNIS_PASSWORD: ${{ secrets.TENNIS_PASSWORD }}
        TENNIS_USERNAME2: ${{ secrets.TENNIS_USERNAME2 }}
        TENNIS_PASSWORD2: ${{ secrets.TENNIS_PASSWORD2 }}
        CARD_NUMBER: ${{ secrets.CARD_NUMBER }}
        CARD_EXPIRY: ${{ secrets.CARD_EXPIRY }}
        CARD_CVC: ${{ secrets.CARD_CVC }}
        BOOKING_DATE: ${{ inputs.date }}
        BOOKING_HOUR: ${{ inputs.hour }}
        ACCOUNT: ${{ inputs.account }}
      run: python main.py
    
    - name: Upload logs and screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: booking-logs-${{ inputs.date }}-${{ inputs.hour }}h-account${{ inputs.account }}
        path: |
          *.log
          *.png
        retention-days: 7
